### ISSUE TITLE
slides show up in overview with much to large bounding box

### ISSUE THREAD

**Issue by Chaos99** [tantaman/Strut#317] opened 2015-01-08 10:08 UTC
(this is for the demo server implementation at http://strut.io/editor/ using Google Chrome 40.0.2214.69 (Official Build) beta-m)

Slides that look normal in the slide editor show up with weird dimensions in the overview.
width is normal, height is a multiple of the original height. The content is rendered on top in the overview, but placed in the middle of the bounding box during presentation.

![image](https://cloud.githubusercontent.com/assets/582663/5660979/9551e9f4-9726-11e4-86ce-3a9ae15d7780.png)

The presentation is locally saved and can be submitted for debugging.

**Comment by mwcz** [comment] 2015-01-08 19:37
This is a dupe of #285 and is fixed in #314 (not merged yet).  You're welcome to use [my strut instance](http://strut-mwcz.rhcloud.com/) which includes the patch.

**Comment by mwcz** [comment] 2015-01-11 00:08
#314 is merged now, this can be closed

**Closed** 2022-11-11 20:56 UTC
